ObligWeb-master/WebOblig1/WebOblig1/Controllers/KundeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebOblig1.Model;
using WebOblig1.BLL;

namespace WebOblig1.Controllers {
    public class KundeController : Controller {
        // Avgjøre dependency injection
        private IKundeLogikk _kundeBLL;

        public KundeController() {
            _kundeBLL = new BankDB_BLL();
        }

        public KundeController(IKundeLogikk stub) {
            _kundeBLL = stub;
        }

        public ActionResult Index()  {
            Session["LoggetInn"] = false;
            return View();
        }

        public ActionResult LoggInn() {
            return View();
        }


        public JsonResult LoggInnAjax(DomenePerson person) {
            // sjekk database for passord
            if (_kundeBLL.Bruker_i_DB(person)) {
                Session["pnr"] = person.personnummer;
                return Json( "OK", JsonRequestBehavior.AllowGet);
            } else {
                Session["LoggetInn"] = false;
                return Json("FEIL", JsonRequestBehavior.AllowGet);
             }
        }

        public JsonResult SjekkDummyID(string id) {
            if (Sikkerhet.validerdummyID(id)) {
                Session["LoggetInn"] = true;
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            return Json("FEIL", JsonRequestBehavior.AllowGet);
        }

    }
}

ObligWeb-master/WebOblig1/WebOblig1/Views/Kunde/DummyIDModal.cshtml
<div id="dummymodal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background:#5C97BF;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Logg inn med BankID</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <h2>BankID</h2>
                    <form>
                        <div class="form-group">
                            <div class="col-xs-2">
                                <label for="ex1">(HINT: 12345)</label>
                                <input class="form-control" id="dummykode" type="text" placeholder="12345">
                                <div id="feilKode" class="text-danger"></div>
                            </div>
                        </div>
                    </form>
                </div>

                
            </div>
            <div class="modal-footer" style="background:#5C97BF;">
                <button type="button" class="btn btn-success" id="bekreftModalKnapp">Bekreft</button>
                <button type="button" class="btn knapp-fare" data-dismiss="modal">Avbryt</button>

            </div>
        </div>
    </div>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/Kunde/Index.cshtml
        
<header id="myCarousel" class="carousel slide">

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('WebOblig1/Content/images/nettbankbildet.jpg');"></div>
            <div class="carousel-caption">
                <h2>Låne i høst?</h2>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('WebOblig1/Content/images/nettbankbildet2.jpg');"></div>
            <div class="carousel-caption">
                <h2>Ny forsikring til bilen</h2>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('WebOblig1/Content/images/nettbankbildet3.jpg');"></div>
            <div class="carousel-caption">
                <h2>Få kundeutbytte i dag</h2>
            </div>
        </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>

<div class="container">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="page-header text-center">
            <h1>Nå må du begynne å spare</h1>
        </div>

        <p class="lead text-center">
            Ledetekst sier det lønner seg å spare.
        </p>
        <p class="text-center">
            Ifølge Verdipapirfondenes forening (VFF) har det vært en kraftig økning i antall spareavtaler i aksje- og kombinasjonsfond i første halvår 2015.

            Det ble opprettet nesten 50.000 nye avtaler om fast sparing i verdipapirfond i løpet av årets seks første måneder, og totalt har
            nordmenn nå omtrent 760.000 slike avtaler om trekk av et fast beløp fra bankkontoen hver måned, som settes i aksje- eller kombinasjonsfond, ifølge VFF.
        </p>
    </div>
</div>

<div class="divider" id="section2"></div>
<section class="bg-1">
    <div class="col-sm-6 col-sm-offset-3 text-center"><h2 style="padding:20px;background-color:rgba(5,5,5,.8)">Et lån gir bedre fritid</h2></div>
</section>

<div class="divider"></div>

<div class="container" id="section3">
    <div class="col-sm-8 col-sm-offset-2 text-center">
        <h1>Vi som jobber i Nettbank C#</h1>

        <p>
            For oss som jobber i Nettbank C# er det du som er viktigst.
            Kundefokus setter sitt preg alt vi jobber med hver eneste dag, og vi vil at du skal være fornøyd.
            Nettbank C# startet i 2016, som den første rene nettbanken i Norge. 
            Norsk Kundebarometer har kåret oss til banken med de mest fornøyde kundene hele 15 år på rad. 
            Vi jobber hardt for å yte god kundeservice, være brukervennlige og ikke minst ha gode priser.
        </p>

        <hr>

        <img src="http://freddielarsson.se/wp-content/uploads/2013/11/effektiv-som-ledare.png" class="img-responsive">

        <hr>
    </div><!--/col-->
</div><!--/container-->

<div class="divider"></div>

<section class="bg-3" id="section4">
    <div class="col-sm-6 col-sm-offset-3 text-center"><h2 style="padding:20px; background-color:rgba(5,5,5,.8)">Få bedre økonomi &amp; la dine penger jobbe i vår bank</h2></div>
</section>

<div class="divider" id="section5"></div>

<ul class="nav pull-right scroll-top">
    <li><a href="#" title="Scroll to top"><i class="glyphicon glyphicon-chevron-up"></i></a></li>
</ul>
<div id="footer">
    <div class="container">
        <p class="text-muted">Obligatorisk oppgave - Webapplikasjoner</p>
    </div>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/Kunde/LoggInn.cshtml
@model WebOblig1.Model.DomenePerson

@Html.Partial("DummyIDModal")

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="container">
        <hr />
        <div id="logginnSkjema" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Logg inn i nettbank</div>
                    <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Glemt passord?</a></div>
                </div>
                <div style="padding-top:30px" class="panel-body">
                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    <form id="loginform" class="form-horizontal" role="form" method="post">
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @Html.EditorFor(model => model.personnummer, new { htmlAttributes = new { @class = "form-control", @id = "persnrID", placeholder = "Personnummer" } })
                        </div>
                        <div style="margin-bottom: 35px" class="text-danger">
                            <p id="feilPnr"></p>
                        </div>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            @Html.EditorFor(model => model.passord, new { htmlAttributes = new { @class = "form-control", @id = "passordID", placeholder = "Passord" } })
                        </div>
                        <div style="margin-bottom: 35px" class="text-danger">
                            <p id="feilPassord"></p>
                        </div>
                        <div style="margin-top:10px" class="form-group">
                            <!-- Knapper -->
                            <div class="col-sm-12 controls">
                                <a href="" onclick="validerAlle()" class="btn btn-md btn-success" id="dummyknapp" data-toggle="modal" data-dummymodal="true" title="Logg inn som kunde">
                                    <span class="glyphicon glyphicon-log-in"></span>
                                </a>
                                <a id="btn-fblogin" href="@Url.Action("Index", "Kunde")" class="btn btn-danger" title="Til forside">
                                    <span class="glyphicon glyphicon-home"></span> 
                                </a>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-12 control">
                                <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                    <a href="#" onClick="$('#logginnSkjema').hide(); $('#adminSkjema').show()">
                                        <h3>Logg inn som administrator</h3>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!--Registreringsskjema-->
        <div id="adminSkjema" style="display:none; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Logg inn som admin</div>
                    <div style="float:right; font-size: 85%; position: relative; top:-10px">
                        <a id="signinlink" href="#" onclick="$('#adminSkjema').hide(); $('#logginnSkjema').show()">Logg inn</a>
                    </div>
                </div>
                <div class="panel-body">
                    <form id="signupform" class="form-horizontal" role="form">

                        <div id="signupalert" style="display:none" class="alert alert-danger">
                            <p>Error:</p>
                            <span></span>
                        </div>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @Html.EditorFor(model => model.personnummer, new { htmlAttributes = new { @class = "form-control", @id = "persnrAdminID", placeholder = "Personnummer" } })
                        </div>
                        <div style="margin-bottom: 35px" class="text-danger">
                            <p id="feilPnr"></p>
                        </div>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            @Html.EditorFor(model => model.passord, new { htmlAttributes = new { @class = "form-control", @id = "passordAdminID", placeholder = "Passord" } })
                        </div>
                        <div style="margin-bottom: 35px" class="text-danger">
                            <p id="feilPassord"></p>
                        </div>
                        <div style="margin-top:10px" class="form-group">
                            <!-- Knapper -->
                            <div class="col-sm-12 controls">
                                <a href="" onclick="validerAlle('admin')" 
                                   class="btn btn-md btn-success" id="dummyknapp" data-toggle="modal" data-dummymodal="true" title="Logg inn som administrator"><span class="glyphicon glyphicon-log-in"></span></a>
                                <a id="btn-fblogin" href="@Url.Action("Index", "Kunde")" class="btn btn-danger " title="Til forside"><span class="glyphicon glyphicon-home"></span></a>
                            </div>

                        </div>

                       
                      </form>
                </div>
            </div>
        </div>
    </div>
}