ObligWeb-master/WebOblig1/WebOblig1/Controllers/MinSideController.cs
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebOblig1.Model;
using WebOblig1.BLL;
using System.Web.Script.Serialization;
using System.Web.Security;
using System;

namespace WebOblig1.Controllers
{
    public class MinSideController : Controller {

        // Avgjøre dependency injection
        private IKundeLogikk _kundeBLL;

        public MinSideController() {
            _kundeBLL = new BankDB_BLL();
        }

        public MinSideController(IKundeLogikk stub) {
            _kundeBLL = stub;
        }

        public ActionResult KontoOversikt() {
            if (Session["LoggetInn"] != null) {
               if ((bool)Session["LoggetInn"]) {
                    string pnr = (string)Session["pnr"];
                    var funnetKunde = _kundeBLL.KontoOversikt(pnr);
                    return View(funnetKunde);
                }
            }
            return RedirectToAction("LoggInn", "Kunde");
        }
        
        public ActionResult NyBetaling() {
            if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {
                    return View();
                }
            }
            return RedirectToAction("LoggInn", "Kunde");
        }
        
        public ActionResult VisBetalinger() {
            if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {
                    return View(_kundeBLL.VisUtforteBetalinger((string)Session["pnr"]));
                }
            }
            return RedirectToAction("LoggInn", "Kunde");
        }

        public JsonResult hentNavn() {
            return Json(_kundeBLL.hentNavn((string)Session["pnr"]), JsonRequestBehavior.AllowGet);
        } 
        
        public ActionResult VisFremtidigeBetalinger() {
            if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {
                    return View(_kundeBLL.VisFremtidigeBetalinger((string)Session["pnr"]));
                }
            }
            return RedirectToAction("LoggInn", "Kunde");
        }

        public void SlettBetaling(int bID) {
            _kundeBLL.SlettBetaling(bID);
        }

        public ActionResult EndreBetaling(int bID) {
            if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {
                    var betaling = _kundeBLL.HentBetaling(bID);
                    if (betaling != null) {
                        return View(betaling);
                    }
                    return View(); // Burde vært en tilbakemelding her.
                }
            }
            return RedirectToAction("LoggInn", "Kunde");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EndreBetaling(DomeneBetaling betaling) {
            if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {
                    if (ModelState.IsValid) {
                        _kundeBLL.EndreBetaling(betaling);
                        return RedirectToAction("VisFremtidigeBetalinger");
                    } else {
                        // ModelState ikke valid
                        return View(); // Feilmelding?
                    }

                } else {
                    return RedirectToAction("LoggInn", "Kunde");
                }
            } else {
                return RedirectToAction("LoggInn", "Kunde");
            }
        }

        public ActionResult LoggUt() {
            Session["LoggetInn"] = false;
            Session.Abandon();
            Session.RemoveAll();

            FormsAuthentication.SignOut();

            this.Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            this.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            this.Response.Cache.SetNoStore();
            return RedirectToAction("Index", "Kunde");
        }

        public JsonResult NyAjaxBetaling(DomeneBetaling b) {
            if (_kundeBLL.NyBetaling(b, (string)Session["pnr"]) == "OK") {
                return Json("OK", JsonRequestBehavior.AllowGet);
            } else if (_kundeBLL.NyBetaling(b, (string)Session["pnr"]) == "DATOFEIL") { 
                return Json("DATOFEIL", JsonRequestBehavior.AllowGet);
            } else {
                return Json("FEIL", JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult hentAlleKonti() {
            return Json(_kundeBLL.VisMineKonti((string)Session["pnr"]), JsonRequestBehavior.AllowGet);
        }

        public JsonResult hentKontoInfo(string knr) {
            return Json(_kundeBLL.HentMinKonto(knr, (string)Session["pnr"]), JsonRequestBehavior.AllowGet);
        }
    }

    /* MAL FOR Å SPERRE FOR INNLOGGING. BRUK PÅ NYE SIDER SOM LAGES
     * if (Session["LoggetInn"] != null) {
                if ((bool)Session["LoggetInn"]) {

                }
            }
            return RedirectToAction("LoggInn", "Kunde");
     * */
}

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/EndreBetaling.cshtml
@model WebOblig1.Model.DomeneBetaling

@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}
<div class="container" style="background-color:#eaeaea">
    <h2 class="overskrift-h2">Endre betaling</h2>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="col-md-12">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.betalingsId)
            @Html.HiddenFor(model => model.fraKonto)

            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.tilKonto)
                    @Html.EditorFor(model => model.tilKonto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tilKonto, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.dato)
                    @Html.EditorFor(model => model.dato, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dato, "", new { @class = "text-danger" })
                </div>
            </div>
                <div class="form-group col-lg-3">
                    @Html.LabelFor(model => model.kid)
                    @Html.EditorFor(model => model.kid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.kid, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-lg-3">
                    @Html.LabelFor(model => model.belopKroner)
                    @Html.EditorFor(model => model.belopKroner, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.belopKroner, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-lg-1">
                    @Html.LabelFor(model => model.belopOrer)
                    @Html.EditorFor(model => model.belopOrer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.belopOrer, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-lg-6">
                    @Html.LabelFor(model => model.melding)
                    @Html.EditorFor(model => model.melding, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.melding, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-lg-12">
                    <input type="submit" value="Lagre" class="btn btn-success" />
                    <a href="@Url.Action("VisFremtidigeBetalinger", "MinSide")" class="btn btn-md btn-danger" id="endreKnapp">Avbryt</a>
             </div>
        </div>
}
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/KontoInfoModal.cshtml
<div id="visKontoInfoModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background:#5C97BF;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" style="color:white;">Informasjon om din konto</h4>
            </div>
            <div class="modal-body">
                <div id="infomodal">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Lukk</button>

            </div>
        </div>
    </div>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/KontoOversikt.cshtml
@model WebOblig1.Model.DomenePerson

@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}

    <div class="container">
        <h2 class="overskrift-h2">Min Oversikt</h2>
        <div>
            <div class="col-sm-4 disponibelt">
                <h3>Disponibelt:</h3>
                <h3 style="margin-top:0;margin-bottom:0;">kr @{
                    double sum = 0;
                    foreach (var konto in Model.konti) { sum += konto.saldo; }
                    @sum
                },-</h3>
            </div>
            <div class="col-sm-4 disponibelt2">
                <h3>Trukket i kreditt:</h3>
                <h3 style="margin-top:0;margin-bottom:0;">kr 0 ,-</h3></div>
            <div class="col-sm-4 disponibelt3">
                <h3>Sum lån:</h3>
                <h3 style="margin-top:0;margin-bottom:0;">kr 0 ,-</h3></div>
        </div>
        <div>
            <table class="table tables-bordered tabell-utseendet">
                <tr class="tabell-rad-overskrift">
                    <th>Kontonavn:</th>
                    <th>Kontonummer:</th>
                    <th>Saldo:</th>
                </tr>
                @foreach (var konto in Model.konti) {
                    <tr class="td-hover">
                        <td>@konto.kontonavn</td>
                        <td>@konto.kontonummer</td>
                        <td>@konto.saldo</td>
                    </tr>
                }
            </table>
        </div>
    </div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/NyBetaling.cshtml
@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}
@Html.Partial("TekniskFeilModal")

<div class="container" style="background-color:#eaeaea">
    <form method="post">
        <div class="col-md-12">
            <h3>Registrer en ny betaling</h3>
            <hr />
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <label>Fra kontonummer</label>
                    <select class="form-control" id="mineKonti"></select>
                </div>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <label>Til kontonummer</label>
                    <input type="text" class="form-control" id="tilKonto" placeholder="Til kontonummer">
                <div class="form-group text-danger">
                    <p id="feilTilKonto"></p>
                </div>
                </div>                
            </div>

                <div class="form-group col-lg-3">
                    <label>Dato</label>
                    <input type="date" class="form-control" id="dato">
                    <div class="form-group text-danger">
                        <p id="feilDato"></p>
                    </div>
                </div>
                        
                <div class="form-group col-lg-3">
                    <label>KID</label>
                    <input type="text" class="form-control" id="kid" placeholder="KID">
                    <div class="form-group text-danger">
                        <p id="feilKid"></p>
                    </div>
                </div>


                <div class="form-group col-lg-2">
                    <label>Kroner</label>
                    <input type="text" class="form-control" id="belopKroner" placeholder="Kroner">
                    <div class="form-group text-danger">
                        <p id="feilKroner"></p>
                    </div>
                </div>


                <div class="form-group col-lg-1">
                    <label>Øre</label>
                    <input type="text" class="form-control" id="belopOrer" value="00">
                    <div class="form-group text-danger">
                        <p id="feilOre"></p>
                    </div>
                </div>

            <div class="form-group col-lg-12"></div>
                <div class="form-group col-lg-6">
                    <label>Melding</label>
                    <input type="text" class="form-control" id="melding" placeholder="Melding">
                    <div class="form-group text-danger">
                        <p id="feilMeld"></p>
                    </div>
                </div>
            
                <div class="form-group col-lg-12">
                    <a href="" onclick="validerAlleReg()" class="btn knappLagre" id="enNyBet" data-toggle="modal" data-tekniskFeilmodal="true">Lagre</a>
                    <a id="btn-fblogin" href="@Url.Action("KontoOversikt", "MinSide")" class="btn knappAvbryt">Avbryt</a>
                </div>
            </div>
    </form>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/VisBetalinger.cshtml
@model List<WebOblig1.Model.DomeneBetaling>

@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}
@Html.Partial("KontoInfoModal")
<div class="container">
    <h2 class="overskrift-h2">Utførte Betalinger</h2>
    <table class="table tables-bordered tabell-utseendet">
        <tr class="tabell-rad-overskrift">
            <th>
                @Html.DisplayNameFor(model => model[0].betalingsId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].dato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].fraKonto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].tilKonto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].belopKroner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].kid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].melding)
            </th>
        </tr>

        @foreach (var item in Model) {
            <tr class="td-hover">
                <td>
                    @Html.DisplayFor(modelItem => item.betalingsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dato)
                </td>
                <td>
                    <a class="kontoLink" id="@item.fraKonto" href="#" onclick="visKontoInfo(this.id)">
                        @Html.DisplayFor(modelItem => item.fraKonto)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tilKonto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.belopKroner)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.kid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.melding)
                </td>
            </tr>
        }

    </table>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/VisFremtidigeBetalinger.cshtml
@model List<WebOblig1.Model.DomeneBetaling>

@{
    Layout = "~/Views/Shared/_MinLayout.cshtml";
}
@Html.Partial("sletteVindu")
@Html.Partial("KontoInfoModal")
<div class="container">
    <h2 class="overskrift-h2">Forfallsregister</h2>
    <table class="table tables-bordered tabell-utseendet">
        <tr class="tabell-rad-overskrift">
            <th>
                @Html.DisplayNameFor(model => model[0].betalingsId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].dato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].fraKonto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].tilKonto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].belopKroner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].kid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].melding)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr class="td-hover">
                <td>
                    @Html.DisplayFor(modelItem => item.betalingsId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dato)
                </td>
                <td>
                   <a class="kontoLink" id="@item.fraKonto" href="#" onclick="visKontoInfo(this.id)">
                    @Html.DisplayFor(modelItem => item.fraKonto)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tilKonto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.belopKroner)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.kid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.melding)
                </td>
                <td>
                    <div id="flyt-til-hoyre">
                        <a href="#sletteModal" class="btn btn-md knapp-fare" id="sletteKnapp"
                           data-dato="@Html.DisplayFor(modelItem => item.dato)"
                           data-id="@item.betalingsId"
                           data-fra="@item.fraKonto" data-toggle="modal" data-sletteModal="true">Slett</a>
                        @Html.ActionLink("Endre", "EndreBetaling", new { bID = item.betalingsId }, new { @class = "btn knapp-endre" })
                    </div>
                    
                </td>
            </tr>
            
        }

    </table>
</div>

ObligWeb-master/WebOblig1/WebOblig1/Views/MinSide/sletteVindu.cshtml
<div id="sletteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background:#5C97BF;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" style="color:white;">Bekreft sletting</h4>
            </div>
            <div class="modal-body">
                <p>Vennligst bekreft at følgende betaling skal slettes :</p>
                <div id="slettBetaling">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal" id="sletteModalKnapp">Slett</button>
                <button type="button" class="btn knapp-fare" data-dismiss="modal">Angre</button>
                
            </div>
        </div>
    </div>
</div>